name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install dependencies and build app
        run: | 
          npm ci
          npm run build --if-present
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 rm s3://sandbox.fraserbenjamin.com/json
          aws s3 sync ./build s3://sandbox.fraserbenjamin.com/json
          
      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id EA9OVXGN7WPEA --paths '/json/*';
